=== culturegouv/octave/docuteam-packer-dist/src/main/octave-resources/config/csv-sip-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:matterhorn="http://docuteam.ch/matterhorn"
           xmlns="ch:docuteam:mapping:csv" targetNamespace="ch:docuteam:mapping:csv"
    elementFormDefault="qualified">
    <xs:include schemaLocation="csv-format.xsd"/>

    <xs:import
            namespace="http://docuteam.ch/matterhorn"
            schemaLocation="matterhorn-field-type.xsd"/>

    <xs:element name="sipImportTableConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="csvFormat"/>
                <xs:element ref="sipImportColumnMapping" minOccurs="0"/>
                <xs:element ref="sipImportMetadataColumnMapping" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sipImportColumnMapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sipImportColumn" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sipImportMetadataColumnMapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sipImportMetadataColumn" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sipImportColumn">
        <xs:annotation>
            <xs:documentation>Specify a mapping indicating the header of a column from the CSV file and its purpose for the SIP creation</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="tableHeaderLabel" use="required" type="xs:string"/>
            <xs:attribute name="paramID" use="required" type="paramType"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="paramType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ID"/>
            <xs:enumeration value="parentID"/>
            <xs:enumeration value="path"/>
            <xs:enumeration value="descriptionLevel"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="checksum"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="sipImportMetadataColumn">
        <xs:annotation>
            <xs:documentation>Specify a mapping indicating the header of a column from the CSV file and its corresponding metadata field in levels.xml</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="tableHeaderLabel" use="required" type="xs:string"/>
            <xs:attribute name="matterhornMetsAccessorID" use="required" type="matterhorn:matterhornFieldType"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== culturegouv/octave/docuteam-packer/src/test/resources/config/csv-sip-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<sipImportTableConfig
        xmlns="ch:docuteam:mapping:csv"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="ch:docuteam:mapping:csv csv-sip-mapping.xsd">

    <csvFormat>
        <charset>UTF-8</charset>
        <delimiter>;</delimiter>
        <quoteCharacter>&quot;</quoteCharacter>
    </csvFormat>

    <sipImportColumnMapping>
        <sipImportColumn tableHeaderLabel="ID" paramID="ID"/>
        <sipImportColumn tableHeaderLabel="ParentID" paramID="parentID"/>
        <sipImportColumn tableHeaderLabel="File" paramID="path"/>
        <sipImportColumn tableHeaderLabel="DescriptionLevel" paramID="descriptionLevel"/>
        <sipImportColumn tableHeaderLabel="Title" paramID="title"/>
    </sipImportColumnMapping>

    <sipImportMetadataColumnMapping>
        <sipImportMetadataColumn tableHeaderLabel="Identifier" matterhornMetsAccessorID="refCode"/>
        <sipImportMetadataColumn tableHeaderLabel="Creator" matterhornMetsAccessorID="origination"/>
        <sipImportMetadataColumn tableHeaderLabel="Subject" matterhornMetsAccessorID="subjectGeneral"/>
        <sipImportMetadataColumn tableHeaderLabel="Description" matterhornMetsAccessorID="scopeContent"/>
        <sipImportMetadataColumn tableHeaderLabel="Publisher" matterhornMetsAccessorID="publisher"/>
        <sipImportMetadataColumn tableHeaderLabel="Contributor" matterhornMetsAccessorID="involved"/>
        <sipImportMetadataColumn tableHeaderLabel="Date" matterhornMetsAccessorID="date"/>
        <sipImportMetadataColumn tableHeaderLabel="Type" matterhornMetsAccessorID="objectType"/>
        <sipImportMetadataColumn tableHeaderLabel="Format" matterhornMetsAccessorID="format"/>
        <sipImportMetadataColumn tableHeaderLabel="Source" matterhornMetsAccessorID="accessNr"/>
        <sipImportMetadataColumn tableHeaderLabel="Language" matterhornMetsAccessorID="language"/>
        <sipImportMetadataColumn tableHeaderLabel="Relation" matterhornMetsAccessorID="relatedMaterial"/>
        <sipImportMetadataColumn tableHeaderLabel="Coverage" matterhornMetsAccessorID="geogName"/>
        <sipImportMetadataColumn tableHeaderLabel="Rights" matterhornMetsAccessorID="accessPolicy"/>
    </sipImportMetadataColumnMapping>

</sipImportTableConfig>
